export const BASE_LOGIC = 'BASE_LOGIC';



export const GET_USERS = 'GET_USER'
export const GET_USERS_REQUESTED = 'GET_USER_REQUESTED'
export const GET_USERS_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USER_FAILURE'


/** LOGIN */
export const GET_DOMAINS = 'GET_DOMAINS'
export const GET_DOMAINS_REQUESTED = 'GET_DOMAINS_REQUESTED'
export const GET_DOMAINS_SUCCESS = 'GET_DOMAINS_SUCCESS'
export const GET_DOMAINS_FAILURE = 'GET_DOMAINS_FAILURE'
export const LOGIN = 'LOGIN';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const UNAUTHENTICATION = 'UNAUTHENTICATION'

/** ITEM TYPE */
export const SAVE_ITEM_TYPE = 'SAVE_ITEM_TYPE'
export const SAVE_ITEM_TYPE_REQUESTED = 'SAVE_ITEM_TYPE_REQUESTED'
export const SAVE_ITEM_TYPE_SUCCESS = 'SAVE_ITEM_TYPE_SUCCESS'
export const SAVE_ITEM_TYPE_FAILURE = 'SAVE_ITEM_TYPE_FAILURE'


export const GET_ITEM_TYPE = 'GET_ITEM_TYPE'
export const GET_ITEM_TYPE_REQUESTED = 'GET_ITEM_TYPE_REQUESTED'
export const GET_ITEM_TYPE_SUCCESS = 'GET_ITEM_TYPE_SUCCESS'
export const GET_ITEM_TYPE_FAILURE = 'GET_ITEM_TYPE_FAILURE'
/** ORDER */
export const SAVE_ORDER= 'SAVE_ORDER'
export const SAVE_ORDER_REQUESTED = 'SAVE_ORDER_REQUESTED'
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS'
export const SAVE_ORDER_FAILURE = 'SAVE_ORDER_FAILURE'
/** CART */
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const REMOVE_ITEM_TO_CART = 'REMOVE_ITEM_TO_CART'
export const EDIT_ITEM_TO_CART = 'EDIT_ITEM_TO_CART'

export const SAVE_CART= 'SAVE_CART'
export const SAVE_CART_REQUESTED = 'SAVE_CART_REQUESTED'
export const SAVE_CART_SUCCESS = 'SAVE_CART_SUCCESS'
export const SAVE_CART_FAILURE = 'SAVE_CART_FAILURE'

/** ITEM*/
export const GET_ITEM= 'GET_ITEM'
export const GET_ITEM_REQUESTED = 'GET_ITEM_REQUESTED'
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS'
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE'

export const GET_ITEMS= 'GET_ITEMS'
export const GET_ITEMS_REQUESTED = 'GET_ITEMS_REQUESTED'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE'

export const SAVE_ITEM= 'SAVE_ITEM'
export const SAVE_ITEM_REQUESTED = 'SAVE_ITEM_REQUESTED'
export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS'
export const SAVE_ITEM_FAILURE = 'SAVE_ITEM_FAILURE'


export const SEARCH_ITEM = 'SEARCH_ITEM';
export const SEARCH_ITEM_REQUESTED = 'SEARCH_ITEM_REQUESTED';
export const SEARCH_ITEM_SUCCESS = 'SEARCH_ITEM_SUCCESS';
export const SEARCH_ITEM_FAILURE = 'SEARCH_ITEM_FAILURE';
