export const BASE_LOGIC = 'BASE_LOGIC';


/** ISSUE */
export const GET_WEEKS = 'GET_WEEKS'
export const GET_WEEKS_REQUESTED = 'GET_WEEKS_REQUESTED'
export const GET_WEEKS_SUCCESS = 'GET_WEEKS_SUCCESS'
export const GET_WEEKS_FAILURE = 'GET_WEEKS_FAILURE'

export const GET_ISSUES_BY_WEEK = 'GET_ISSUES_BY_WEEK'
export const GET_ISSUES_BY_WEEK_REQUESTED = 'GET_ISSUES_BY_WEEK_REQUESTED'
export const GET_ISSUES_BY_WEEK_SUCCESS = 'GET_ISSUES_BY_WEEK_SUCCESS'
export const GET_ISSUES_BY_WEEK_FAILURE = 'GET_ISSUES_BY_WEEK_FAILURE'

/** ROLE */



export const CREATE_USER = 'CREATE_USER';



export const GET_ROLES = 'GET_ROLES'
export const GET_ROLES_REQUESTED = 'GET_ROLES_REQUESTED'
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS'
export const GET_ROLES_FAILURE = 'GET_ROLES_FAILURE'

export const GET_USERS = 'GET_USERS'
export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

/** LOGIN */
export const GET_DOMAINS = 'GET_DOMAINS'
export const GET_DOMAINS_REQUESTED = 'GET_DOMAINS_REQUESTED'
export const GET_DOMAINS_SUCCESS = 'GET_DOMAINS_SUCCESS'
export const GET_DOMAINS_FAILURE = 'GET_DOMAINS_FAILURE'
export const LOGIN = 'LOGIN';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const UNAUTHENTICATION = 'UNAUTHENTICATION'

/** PROJECT */
export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_PROJECTS_REQUESTED = 'GET_PROJECTS_REQUESTED'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE'

export const SAVE_PROJECTS = 'SAVE_PROJECTS'
export const SAVE_PROJECTS_REQUESTED = 'SAVE_PROJECTS_REQUESTED'
export const SAVE_PROJECTS_SUCCESS = 'SAVE_PROJECTS_SUCCESS'
export const SAVE_PROJECTS_FAILURE = 'SAVE_PROJECTS_FAILURE'
/** ITEM TYPE */
export const SAVE_ITEM_TYPE = 'SAVE_ITEM_TYPE'
export const SAVE_ITEM_TYPE_REQUESTED = 'SAVE_ITEM_TYPE_REQUESTED'
export const SAVE_ITEM_TYPE_SUCCESS = 'SAVE_ITEM_TYPE_SUCCESS'
export const SAVE_ITEM_TYPE_FAILURE = 'SAVE_ITEM_TYPE_FAILURE'


export const GET_ITEM_TYPE = 'GET_ITEM_TYPE'
export const GET_ITEM_TYPE_REQUESTED = 'GET_ITEM_TYPE_REQUESTED'
export const GET_ITEM_TYPE_SUCCESS = 'GET_ITEM_TYPE_SUCCESS'
export const GET_ITEM_TYPE_FAILURE = 'GET_ITEM_TYPE_FAILURE'


/** CART */
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const REMOVE_ITEM_TO_CART = 'REMOVE_ITEM_TO_CART'
export const EDIT_ITEM_TO_CART = 'EDIT_ITEM_TO_CART'
